name: build

on:
  workflow_dispatch: {}
  push:
    branches: [ main, develop ]

env:
  PROJECT_ID: bright-meridian-316511

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: env
        id: env
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
          if [ "$REF" = "refs/heads/main" ]; then
              echo "::set-output name=app_env::prod"
          else
              echo "::set-output name=app_env::dev"
          fi
        env:
          REF: ${{ github.ref }}

      # Build and push images to Google Container Registry
      - name: Build image
        run: docker build --progress=plain -t "gcr.io/${PROJECT_ID}/subsquid-network-points-app-${APP_ENV}:${TAG}" -t "gcr.io/${PROJECT_ID}/subsquid-network-points-app-${APP_ENV}:latest" .
        env:
          APP_ENV: ${{ steps.env.outputs.app_env }}
          TAG: ${{ steps.env.outputs.tag }}

      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      # steps for push images to gcr
      - name: 'gcloud cli --> docker credential helper'
        run: gcloud auth configure-docker -q

      - name: Push image
        run: |
          docker push "gcr.io/${PROJECT_ID}/subsquid-network-points-app-${APP_ENV}:${TAG}"
          docker push "gcr.io/${PROJECT_ID}/subsquid-network-points-app-${APP_ENV}:latest"
        env:
          APP_ENV: ${{ steps.env.outputs.app_env }}
          TAG: ${{ steps.env.outputs.tag }}
